app: "db-app"

# service
service:
  type: ClusterIP
  protocol: TCP
  port: 5432
  clusterIP: 10.152.183.165
  # nodePort: 32003 

# deployment
replicaCount: 2
container:
  image: dedder98/kubernetes-db
  port: 5432
  pullPolicy: Always

# environment
env:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: psltest
  PGDATA: /var/lib/postgresql/data/pgdata

# volumes
volumes:
  accessModes: ReadWriteOnce

storage:
  className: microk8s-hostpath
  size: 5Gi