apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app }}-config
  labels:
    app: {{ .Values.app }}
data:
  {{- range $key, $value := .Values.env }}
      {{ $key }}: {{ $value | quote }}
  {{- end }}
