apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app }}-config
  labels:
    app: {{ .Values.app }}
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: psltest
