apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service 
  labels:
    app: {{ .Values.app }} 
spec:
  type: {{ .Values.service.type }} 
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.port }} 
      targetPort: {{ .Values.container.port }}
      # nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    app: {{ .Values.app }}