apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service # Sets service name
  labels:
    app: {{ .Values.app }} # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 5432 # Sets port to run the postgres application
      targetPort: 5432
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    app: {{ .Values.app }}