apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service 
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: {{ .Values.service.protocol }} 
    port: {{ .Values.service.port }} 
    targetPort: {{ .Values.container.port }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.app }}