apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-deployment 
  labels:
    app: {{ .Values.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.app }}-regcred
      containers:
      - name: {{ .Values.app }}-container
        imagePullPolicy: Always
        image: {{ .Values.container.image }}
        env:
        - name: FRONTEND_URL
          value: {{ .Values.env.FRONTEND_URL }}
        ports:
        - containerPort: {{ .Values.container.port }}
        # nodeSelector:
        #   kubernetes.io/hostname: hp