app: "backend-app"

# service
service:
  type: NodePort
  protocol: TCP
  port: 4000
  nodePort: 32002

# deployment
replicaCount: 3
container:
  image: dedder98/kubernetes-nodejs
  port: 80

# env
env:
  FRONTEND_URL: http://kube-full.com
  POSTGRES_USER: postgresadmin
  POSTGRES_HOST: 10.152.183.165 # TODO: this is a static ClusterIP. find a better way to do this
  POSTGRES_DB: postgresdb
  POSTGRES_PASSWORD: psltest
  POSTGRES_PORT: 5432

# ingress
ingress:
  url: api.kube-full.com