app: "backend-app"

# service
service:
  type: LoadBalancer
  protocol: TCP
  port: 4000
  nodePort: 32002 # optional for nodeport, service can be accessed by localhost:32001

# deployment
replicaCount: 1
container:
  image: dedder98/kubernetes-nodejs
  port: 80

# env
env:
  FRONTEND_URL: http://kube-full.com
  POSTGRES_USER: postgresadmin
  POSTGRES_HOST: postgres
  POSTGRES_DB: postgresdb
  POSTGRES_PASSWORD: psltest
  POSTGRES_PORT: 5432

# ingress
ingress:
  url: api.kube-full.com