version: "3.8"
services:
  frontend:
    container_name: react-container
    image: dedder98/kubernetes-react
    build: 
      context: ./frontend/app
      dockerfile: Dockerfile.prod
    ports:
      - 32001:80
    depends_on: 
      - backend

  backend:
    container_name: node-container
    image: dedder98/kubernetes-nodejs
    build: ./backend/app
    environment:
      - FRONTEND_URL=http://localhost:32001
    ports:
    - 32002:80

  db:
    container_name: db-container
    image: dedder98/kubernetes-db
    build: ./db
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: admin123
    ports:
    - 32003:5432
    restart: always