version: "3.8"
services:

  frontend:
    container_name: react-container
    image: dedder98/kubernetes-react
    build: 
      context: ./frontend/app
      dockerfile: Dockerfile.prod
    ports:
      - 32001:80
    depends_on: 
      - backend
    networks:
      - my_net

  backend:
    container_name: node-container
    image: dedder98/kubernetes-nodejs
    depends_on:
      - db
    build: 
      context: ./backend/app
      dockerfile: Dockerfile.prod
    environment:
      - FRONTEND_URL=http://localhost:32001
      - POSTGRES_USER=postgresadmin
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=kube-full-db
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_PORT=5432
    ports:
    - 32002:80
    networks:
      - my_net

  db:
    container_name: db-container
    image: dedder98/kubernetes-db
    build: ./db
    hostname: postgres
    environment:
      POSTGRES_DB: kube-full-db
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: admin123
    ports:
    - 32003:5432
    restart: always
    networks:
      - my_net

networks:
  my_net:
    name: my_shared_db