FROM node:19-alpine as builder
WORKDIR /app
COPY package.json . 
COPY yarn.lock .
RUN yarn install 
# TODO: might optimize by only copying the build folder?
COPY . .
RUN yarn build

# stage 2
FROM nginx:1.19.0
WORKDIR /usr/share/nginx/html 
RUN rm -rf ./* 
COPY --from=builder /app/build .
ENTRYPOINT ["nginx", "-g", "daemon off;"]