app: "frontend-app"

# service
service:
  type: NodePort
  protocol: TCP
  port: 3000
  nodePort: 32001 # optional for nodeport, service can be accessed by localhost:32001

# deployment
replicaCount: 3
container:
  image: dedder98/kubernetes-react
  port: 80

# environment variables
env:
  REACT_APP_BACKEND_URL: http://api.kube-full.com

# ingress
ingress:
  url: kube-full.com