name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths: ['backend/app/**']
  pull_request:
    branches: ["main"]
    paths: ['backend/app/**']

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_BACKEND_IMAGE: kubernetes-nodejs

jobs:

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/app
    steps:
    - uses: actions/checkout@v3
    - name: Docker Image for NodeJS-App
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$DOCKER_BACKEND_IMAGE:latest
    - name: Docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Push image
      run: docker push $DOCKER_USER/$DOCKER_BACKEND_IMAGE:latest
