name: Docker Image CI

on:
  push:
    branches: ["master"]
    paths: ['system/db/**']
  pull_request:
    branches: ["master"]
    paths: ['system/db/**']

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_DB_IMAGE: kubernetes-db

jobs:

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: system/db/app
    steps:
    - uses: actions/checkout@v3
    - name: Docker Image for NodeJS-App
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$DOCKER_DB_IMAGE:latest
    - name: Docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Push image
      run: docker push $DOCKER_USER/$DOCKER_BACKEND_IMAGE:latest
